export {
  curriculumModules,
  exerciseCdeSequence,
  exerciseCFiveFinger,
  exerciseDescendCba,
  exerciseFgaAscend,
  exerciseMiddleCFive,
  exerciseRegisterAscendA3C4,
  exerciseRegisterDescendC4G3,
  exerciseRegisterFCG,
  exerciseRegisterF3,
  exerciseRegisterG4,
  exerciseRegisterSteadyReview,
  exerciseRegisterWalk,
  exerciseRepeatedG3,
  exerciseSteadyCDEG,
  exerciseSteadyCFour,
  exerciseSteadyCGFour,
  exerciseSteadyCTwo,
  exercisesById,
  getExerciseById,
  getLessonById,
  getModuleById,
  lessons,
  MODULE_KEYBOARD_FOUNDATIONS,
  MODULE_NOTE_SEQUENCES,
  MODULE_REGISTER_AND_DIRECTION,
} from "./lessons-data";
export type { CurriculumModule } from "./lessons-data";
